###

GET http://localhost:3000/


###

POST http://localhost:3000/sender
Content-Type: application/json  

{
  "senderName": "The Wachowskis",
  "senderEmail": "wachowskis@example.com"
}

###
POST http://localhost:3000/sender
Content-Type: application/json  

{
  "senderName": "Ron_Shaked",
  "senderEmail": "ron_shaked@example.com"
}

###
POST http://localhost:3000/post
Content-Type: application/json

{
  "title": "The Matrix",
  "content": "A computer hacker learns about the true nature of his reality.",
  "sender": "693bcbfeb50c91328886a258"
}

###

POST http://localhost:3000/post
Content-Type: application/json

{
  "title": "Barbie",
  "content": "and ken",
  "sender": "693bcbfeb50c91328886a258"
}

###

PUT http://localhost:3000/post/693bcc91d5c8a3c0c5d3630f
Content-Type: application/json  

{
  "title": "The Matrix Reloaded",
  "content": "The second installment in The Matrix trilogy.",
  "sender": "693b35badb2b2bb5813cde5b"
}

###
DELETE http://localhost:3000/post/693bcc91d5c8a3c0c5d3630f

###
DELETE http://localhost:3000/post

###

GET http://localhost:3000/post?sender=693b35badb2b2bb5813cde5b

###
GET http://localhost:3000/post/693b3616db2b2bb5813cde61

###
DELETE http://localhost:3000/post/693b34c0db2b2bb5813cde51

###
PUT http://localhost:3000/post/693b3616db2b2bb5813cde61
Content-Type: application/json  

{
  "title": "Inception",
  "content": "A mind-bending thriller about dreams within dreams.",
  "sender": "693b334edb2b2bb5813cde30"
}



###
POST http://localhost:3000/comment
Content-Type: application/json

{
  "content": "This post is awesome!!",
  "post": "693b3616db2b2bb5813cde61",
  "sender": "693b334edb2b2bb5813cde30"
}

###
GET http://localhost:3000/comment

###
GET http://localhost:3000/comment?post=693b2f0f735255e9e6158227

###
GET http://localhost:3000/comment/693b313e735255e9e615823a

###
PUT http://localhost:3000/comment/693bd570a3ac5aab38612432
Content-Type: application/json

{
  "content": "Nevermind1 i dont like this post"
}

###
DELETE http://localhost:3000/comment/693bd570a3ac5aab38612432



