//COMMENTS API REQUESTS

### Create a Comment POST http://localhost:3000/comment Content-Type: application/json { "content": "This is a sample comment", "post": "VALID_POST_ID, "sender: "VALID_SENDER_ID" }

### Get All Comments GET http://localhost:3000/comment Content-Type: application/json

### Get Comments for a Specific Post by ID GET http://localhost:3000/comment?post=VALID_POST_ID Content-Type: application/json

### Get Comments for a Specific User by Username GET http://localhost:3000/comment?sender=VALID_SENDER_ID

### Get a Comment for a Specific Comment ID GET http://localhost:3000/comment/VALID_COMMENT_ID 

### Update a Comment PUT http://localhost:3000/comment/VALID_COMMENT_ID Content-Type: application/json { "content": "Updated comment content"}

### Delete a Comment by ID DELETE http://localhost:3000/comments/VALID_COMMENT_ID Content-Type: application/json



//POSTS API REQUESTS

### POST request to create a new post POST http://localhost:3000/post Content-Type: application/json { "title": "post_title", "content": "This is a new post!", "sender": "VALID_SENDER_ID" }

### GET request to fetch all posts GET http://localhost:3000/post 

### GET request to fetch posts by a specific sender GET http://localhost:3000/post?sender=VALID_SENDER_ID 

### GET request to fetch a specific post by ID GET http://localhost:3000/post/VALID_POST_ID 

### PUT request to update a specific post by ID PUT http://localhost:3000/post/VALID_POST_ID Content-Type: application/json { "message": "Updated message content!"}

### DELETE request to delete a specific post by ID DELETE http://localhost:3000/post/VALID_POST_ID

### DELETE request to delete all posts DELETE http://localhost:3000/post